#
# GRAKN.AI - THE KNOWLEDGE GRAPH
# Copyright (C) 2018 Grakn Labs Ltd
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

version: 2.1
commands:
  install-bazel-linux-rbe:
    steps:
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-linux.sh
      - run: bash ./install-bazel-linux.sh && rm ./install-bazel-linux.sh
      - run: curl -OL https://raw.githubusercontent.com/graknlabs/build-tools/master/ci/install-bazel-rbe.sh
      - run: bash ./install-bazel-rbe.sh && rm ./install-bazel-rbe.sh

  run-bazel-rbe:
    parameters:
      command:
        type: string
    steps:
      - run: bazel run @graknlabs_build_tools//ci:run-bazel-rbe -- << parameters.command >>

  run-grakn-server:
    steps:
      - run-bazel-rbe:
          command: bazel build @graknlabs_grakn_core//:assemble-linux-targz
      - run: mkdir dist && tar -xvzf bazel-genfiles/external/graknlabs_grakn_core/grakn-core-all-linux.tar.gz -C ./dist/
      - run: nohup ./dist/grakn-core-all-linux/grakn server start

jobs:
  build:
    machine: true
    working_directory: ~/docs
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run-bazel-rbe:
          command: bazel build //...

  test-query-graql-lang:
    machine: true
    working_directory: ~/docs
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run-bazel-rbe:
          command: bazel test //test/query:graql-lang --test_output=errors

  test-query-graql-java:
    machine: true
    working_directory: ~/docs
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run-bazel-rbe:
          command: bazel test //test/query:graql-java --test_output=errors

  test-example-java:
    machine: true
    working_directory: ~/docs
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run-grakn-server
      - run: bazel test //test/example/java:phone-calls --test_output=errors
      - run: bazel test //test/example/java:social-network --test_output=errors

  test-example-nodejs:
    machine: true
    working_directory: ~/docs
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run-grakn-server
      - run: bazel test //test/example/nodejs:phone-calls --test_output=errors
      - run: bazel test //test/example/nodejs:social-network --test_output=errors

  test-example-python:
    machine: true
    working_directory: ~/docs
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run-grakn-server
      - run: bazel test //test/example/python:phone-calls --test_output=errors
      - run: bazel test //test/example/python:social-network --test_output=errors

  test-links:
    machine: true
    working_directory: ~/docs
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: bazel test //test/links:test --test_output=errors

  release-staging:
    machine: true
    working_directory: ~/docs
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: |
          export RELEASE_DOCS_USERNAME=$REPO_GITHUB_USERNAME_GRABL
          export RELEASE_DOCS_EMAIL=$REPO_GITHUB_EMAIL_GRABL
          export RELEASE_DOCS_TOKEN=$REPO_GITHUB_TOKEN_GRABL
          bazel run @graknlabs_build_tools//ci:release-docs -- development $CIRCLE_SHA1

  release-production:
    machine: true
    working_directory: ~/docs
    steps:
      - install-bazel-linux-rbe
      - checkout
      - run: |
          export RELEASE_DOCS_USERNAME=$REPO_GITHUB_USERNAME_GRABL
          export RELEASE_DOCS_EMAIL=$REPO_GITHUB_EMAIL_GRABL
          export RELEASE_DOCS_TOKEN=$REPO_GITHUB_TOKEN_GRABL
          bazel run @graknlabs_build_tools//ci:release-docs -- master $CIRCLE_SHA1

workflows:
  docs:
    jobs:
      - build
      - test-query-graql-lang
      - test-query-graql-java
      - test-example-java
      - test-example-nodejs
      - test-example-python
      - test-links
      - release-staging:
          filters:
            branches:
              only: development
          requires:
            - build
            - test-query-graql-lang
            - test-query-graql-java
            - test-example-java
            - test-example-nodejs
            - test-example-python
            - test-links
      - release-production:
          filters:
            branches:
              only: master
          requires:
            - build
            - test-query-graql-lang
            - test-query-graql-java
            - test-example-java
            - test-example-nodejs
            - test-example-python
            - test-links